const { Schema, model } = require("mongoose");

const subPageSchema = new Schema(
  {
    name: {
      type: String,
      required: true,
    },
    slug: {
      type: String,
      unique: true,
      required: true,
    },
    page: {
      type: Schema.Types.ObjectId,
      ref: "Page",
      required: true,
    },
    // hero_section: {
    //   type: Object,
    //   heading: String,
    //   sub_heading: String,
    //   heading_summary: String,
    //   button_title: String,
    //   banners: [String],
    //   required: false,
    // },
    professional_it_services: {
      type: Object,
      sub_heading: String,
      heading: String,
      heading_summary: String,
      button_title: String,
      status: {
        type: Boolean,
        enum: [true, false],
        default: false,
      },
      required: false,
    },
    boost_creativity: {
      type: Object,
      sub_heading: String,
      heading: String,
      heading_summary: String,
      button_title: String,
      image: String,
      status: {
        type: Boolean,
        enum: [true, false],
        default: false,
      },
      required: false,
    },
    stand_out: {
      type: Object,
      sub_heading: String,
      heading: String,
      heading_summary: String,
      analytics: Number,
      development: Number,
      solutions: Number,
      button_title: String,
      call_for_help: String,
      card_1: {
        type: Object,
        icon: String,
        title: String,
      },
      card_2: {
        type: Object,
        icon: String,
        title: String,
      },
      card_3: {
        type: Object,
        icon: String,
        title: String,
      },
      card_4: {
        type: Object,
        icon: String,
        title: String,
      },
      status: {
        type: Boolean,
        enum: [true, false],
        default: false,
      },
      required: false,
    },
    companies: {
      type: Object,
      image_1: String,
      image_2: String,
      image_3: String,
      image_4: String,
      status: {
        type: Boolean,
        enum: [true, false],
        default: false,
      },
      required: false,
    },
    // appointment: {
    //   type: Object,
    //   sub_heading: String,
    //   heading: String,
    //   heading_summary: String,
    //   bg_image: String,
    //   bg_form_image: String,
    //   required: false,
    // },
    it_solutions: {
      type: Object,
      sub_heading: String,
      heading: String,
      heading_summary: String,
      button_title: String,
      solution_1: {
        type: [Object],
        icon: String,
        title: String,
        summary: String,
      },
      solution_2: {
        type: [Object],
        icon: String,
        title: String,
        summary: String,
      },
      solution_3: {
        type: [Object],
        icon: String,
        title: String,
        summary: String,
      },
      solution_4: {
        type: [Object],
        icon: String,
        title: String,
        summary: String,
      },
      status: {
        type: Boolean,
        enum: [true, false],
        default: false,
      },
      required: false,
    },
    about_our_work: {
      type: Object,
      sub_heading: String,
      heading: String,
      heading_summary: String,
      button_title: String,
      card_1: {
        type: [Object],
        title: String,
        summary: String,
      },
      card_2: {
        type: [Object],
        title: String,
        summary: String,
      },
      card_3: {
        type: [Object],
        title: String,
        summary: String,
      },
      card_4: {
        type: [Object],
        title: String,
        summary: String,
      },
      status: {
        type: Boolean,
        enum: [true, false],
        default: false,
      },
      required: false,
    },
    // complete_projects: {
    //   type: Object,
    //   sub_heading: String,
    //   heading: String,
    //   heading_summary: String,
    //   required: false,
    // },
    work_process: {
      type: Object,
      sub_heading: String,
      heading: String,
      heading_summary: String,
      process_1: {
        type: [Object],
        icon: String,
        title: String,
        summary: String,
      },
      process_2: {
        type: [Object],
        icon: String,
        title: String,
        summary: String,
      },
      process_3: {
        type: [Object],
        icon: String,
        title: String,
        summary: String,
      },
      process_4: {
        type: [Object],
        icon: String,
        title: String,
        summary: String,
      },
      status: {
        type: Boolean,
        enum: [true, false],
        default: false,
      },
      required: false,
    },
    about_company: {
      type: Object,
      sub_heading: String,
      heading: String,
      heading_summary: String,
      status: {
        type: Boolean,
        enum: [true, false],
        default: false,
      },
      required: false,
    },
  },
  { timestamps: true }
);

const SP = model("SP", subPageSchema);
module.exports = SP;
